### ISSUE TITLE
Missing Beta/V3 API to replace /cc/api/source/reset/{id}

### ISSUE THREAD

**Issue by eabedrapo** [sailpoint-oss/api-specs#28]
Hello,

I noticed that the only way to reset sources is still through {baseURL}/cc/api/source/reset/{id} whose end of life is at the end of this year.

Is this in your backlog for Beta/V3 APIs? Or will you ask customers to contact support when they need to reset their sources after Dec 31st, 2023?

Thanks!

**Comment by tyler-mairose-sp** [comment]
Hello @eabedrapo,

The best place to track deprecation statuses and replacement APIs will be in the deprecations category in the developer community forum. The specific endpoint you mentioned is here: https://developer.sailpoint.com/discuss/t/post-api-source-reset/20497.
