### ISSUE TITLE
[Bug] Role DimensionRefs marked as "string" despite being stored as a "list" in sandbox tenants

### ISSUE THREAD

**Issue by ianphilm** [sailpoint-oss/api-specs#91]
https://github.com/sailpoint-oss/api-specs/blob/f2e96365941414147dba112c044717e2775a7d8f/idn/v3/schemas/access/Role.yaml#L89

Above is the YAML definition. I am unable to use the python SDK V3 (or Beta) API endpoint to list_roles() due to a model validation failure stemming from incorrect/incomplete documentation above. If I attempt to use the SDK to pull back a role with json as follows:
 {
        "id": "bf751c9ffbcc41988ad4b914e869657a",
        "name": "TEST_ROLE_PATCH",
        "created": "2024-10-01T23:05:38.539419Z",
        "modified": "2024-10-01T23:14:25.125243Z",
        "description": "test role meant to test script for patching membership criteria",
        "owner": {
            "type": "IDENTITY",
            "id": "ab25e836dd7740c1985525583525151a",
            "name": "imckenzieadmin"
        },
        "entitlements": [],
        "accessProfiles": [],
        "membership": {
            "type": "STANDARD",
            "criteria": {
                "operation": "OR",
                "key": null,
                "stringValue": null,
                "children": [
                    {
                        "operation": "AND",
                        "key": null,
                        "stringValue": null,
                        "children": [
                            {
                                "operation": "EQUALS",
                                "key": {
                                    "type": "ACCOUNT",
                                    "property": "attribute.JOB_FAMILY",
                                    "sourceId": "2c9180846b0a1a16016b3fed499c1da5"
                                },
                                "stringValue": "BOLOGNA",
                                "children": null
                            },
                            {
                                "operation": "EQUALS",
                                "key": {
                                    "type": "ACCOUNT",
                                    "property": "attribute.JOBCODE",
                                    "sourceId": "2c9180846b0a1a16016b3fed499c1da5"
                                },
                                "stringValue": "666",
                                "children": null
                            }
                        ]
                    },
                    {
                        "operation": "AND",
                        "key": null,
                        "stringValue": null,
                        "children": [
                            {
                                "operation": "EQUALS",
                                "key": {
                                    "type": "ACCOUNT",
                                    "property": "attribute.JOBCODE",
                                    "sourceId": "2c9180846b0a1a16016b3fed499c1da5"
                                },
                                "stringValue": "666",
                                "children": null
                            },
                            {
                                "operation": "EQUALS",
                                "key": {
                                    "type": "ACCOUNT",
                                    "property": "attribute.JOB_FAMILY",
                                    "sourceId": "2c9180846b0a1a16016b3fed499c1da5"
                                },
                                "stringValue": "BOLOGNA",
                                "children": null
                            }
                        ]
                    }
                ]
            },
            "identities": null
        },
        "legacyMembershipInfo": null,
        "enabled": true,
        "requestable": false,
        "accessRequestConfig": {
            "commentsRequired": null,
            "denialCommentsRequired": null,
            "approvalSchemes": []
        },
        "revocationRequestConfig": {
            "approvalSchemes": []
        },
        "segments": [],
        "dimensional": false,
        "dimensionRefs": []
    }

I get the following error:
1 validation error for Role
dimensionRefs
  Input should be a valid string [type=string_type, input_value=[], input_type=list]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type

I do not have this issue in production, where it seems that role.dimensionRefs are stored with a "NULL" value.

**Comment by tyler-mairose-sp** [comment]
Hello @ianphilm, this has been fixed in https://github.com/sailpoint-oss/api-specs/commit/e681732ab2926fafe71721f0cb2ec3c458f6f604 and will be a part of the next SDK release.
